version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27018:27017"  
    volumes:
      - mongodb_data:/data/db

  applicant-bot:
    container_name: bstu-applicant-bot
    build: .
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017  
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS}
    ports:
      - "8000:8000"
    volumes:
      - .:/app 
    command: ["python3", "app/main.py"] 

volumes:
  mongodb_data:
