name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version 

      - name: Check if docker-compose.yml exists
        run: |
          if [ ! -f "./app/docker-compose.yml" ]; then
            echo "docker-compose.yml not found!"
            exit 1
          else
            echo "docker-compose.yml found!"
          fi
          
      - name: Set up environment variables
        run: echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> $GITHUB_ENV

      - name: Build and deploy with Docker Compose
        run: |
          docker-compose -f ./app/docker-compose.yml up --build -d
 
